graph TD
You -- What you care about --> Topic
You -- What you know about --> Topic
You -- What decisions you face --> Topic
Topic -- 7 Templates --> Question/Hypothesis
Topic -- "X is really non-X" --> Question/Hypothesis
Question/Hypothesis -- Search --> Data
Question/Hypothesis -- Browse --> Data